type Station =
  | 'Acton Central'
  | 'Acton Main Line'
  | 'Aldgate'
  | 'Aldgate East'
  | 'Alexandra Palace'
  | 'All Saints'
  | 'Alperton'
  | 'Amersham'
  | 'Anerley'
  | 'Angel'
  | 'Archway'
  | 'Arnos Grove'
  | 'Arsenal'
  | 'Baker Street'
  | 'Balham'
  | 'Bank'
  | 'Barbican'
  | 'Barking'
  | 'Barkingside'
  | 'Barons Court'
  | 'Bayswater'
  | 'Beckton'
  | 'Beckton Park'
  | 'Becontree'
  | 'Belsize Park'
  | 'Bermondsey'
  | 'Bethnal Green'
  | 'Blackfriars'
  | 'Blackhorse Road'
  | 'Blackwall'
  | 'Bond Street'
  | 'Borough'
  | 'Boston Manor'
  | 'Bounds Green'
  | 'Bow Church'
  | 'Bow Road'
  | 'Brent Cross'
  | 'Brixton'
  | 'Bromley-by-Bow'
  | 'Brondesbury'
  | 'Brondesbury Park'
  | 'Buckhurst Hill'
  | 'Burnt Oak'
  | 'Caledonian Road'
  | 'Caledonian Road & Barnsbury'
  | 'Camden Road'
  | 'Camden Town'
  | 'Canada Water'
  | 'Canary Wharf'
  | 'Canning Town'
  | 'Cannon Street'
  | 'Canons Park'
  | 'Chalfont & Latimer'
  | 'Chalk Farm'
  | 'Chancery Lane'
  | 'Charing Cross'
  | 'Chesham'
  | 'Chigwell'
  | 'Chiswick Park'
  | 'Chorleywood'
  | 'Clapham Common'
  | 'Clapham North'
  | 'Clapham South'
  | 'Cockfosters'
  | 'Colindale'
  | 'Colliers Wood'
  | 'Covent Garden'
  | 'Crossharbour'
  | 'Custom House'
  | 'Cutty Sark'
  | 'Cyprus'
  | 'Dagenham East'
  | 'Dagenham Heathway'
  | 'Debden'
  | 'Deptford Bridge'
  | 'Devons Road'
  | 'Dollis Hill'
  | 'Ealing Broadway'
  | 'Ealing Common'
  | "Earl's Court"
  | 'East Acton'
  | 'East Finchley'
  | 'East Ham'
  | 'East India'
  | 'East Putney'
  | 'Eastcote'
  | 'Edgware'
  | 'Edgware Road'
  | 'Elephant & Castle'
  | 'Elm Park'
  | 'Elverson Road'
  | 'Embankment'
  | 'Epping'
  | 'Euston'
  | 'Euston Square'
  | 'Fairlop'
  | 'Farringdon'
  | 'Finchley Central'
  | 'Finchley Road'
  | 'Finsbury Park'
  | 'Farringdon'
  | 'Fulham Broadway'
  | 'Gallions Reach'
  | 'Gants Hill'
  | 'Gloucester Road'
  | 'Golders Green'
  | 'Goldhawk Road'
  | 'Goodge Street'
  | 'Grange Hill'
  | 'Great Portland Street'
  | 'Greenford'
  | 'Green Park'
  | 'Gunnersbury'
  | 'Hainault'
  | 'Hammersmith'
  | 'Hampstead'
  | 'Hanger Lane'
  | 'Harlesden'
  | 'Harrow & Wealdstone'
  | 'Harrow-on-the-Hill'
  | 'Hatton Cross'
  | 'Heathrow Terminals 2 & 3'
  | 'Heathrow Terminal 4'
  | 'Heathrow Terminal 5'
  | 'Hendon Central'
  | 'Heron Quays'
  | 'High Barnet'
  | 'Highbury & Islington'
  | 'Highgate'
  | 'Hillingdon'
  | 'Holborn'
  | 'Holland Park'
  | 'Holloway Road'
  | 'Homerton'
  | 'Hornchurch'
  | 'Hounslow Central'
  | 'Hounslow East'
  | 'Hounslow West'
  | 'Hyde Park Corner'
  | 'Ickenham'
  | 'Ilford'
  | 'Imperial Wharf'
  | 'Island Gardens'
  | 'Kennington'
  | 'Kensal Green'
  | 'Kensington (Olympia)'
  | 'Kentish Town'
  | 'Kentish Town West'
  | 'Kenton'
  | 'Kew Gardens'
  | 'Kilburn'
  | 'Kilburn Park'
  | "King's Cross St. Pancras"
  | 'Kingsbury'
  | 'Kingston'
  | 'Knightsbridge'
  | 'Ladbroke Grove'
  | 'Lambeth North'
  | 'Lancaster Gate'
  | 'Latimer Road'
  | 'Leicester Square'
  | 'Leyton'
  | 'Leytonstone'
  | 'Liverpool Street'
  | 'London Bridge'
  | 'Loughton'
  | 'Maida Vale'
  | 'Manor House'
  | 'Mansion House'
  | 'Marble Arch'
  | 'Marylebone'
  | 'Mile End'
  | 'Mill Hill East'
  | 'Monument'
  | 'Moor Park'
  | 'Moorgate'
  | 'Morden'
  | 'Mornington Crescent'
  | 'Mudchute'
  | 'Neasden'
  | 'Newbury Park'
  | 'North Acton'
  | 'North Ealing'
  | 'North Greenwich'
  | 'North Harrow'
  | 'North Wembley'
  | 'Northfields'
  | 'Northolt'
  | 'Northwick Park'
  | 'Northwood'
  | 'Northwood Hills'
  | 'Notting Hill Gate'
  | 'Oakwood'
  | 'Old Street'
  | 'Osterley'
  | 'Oval'
  | 'Oxford Circus'
  | 'Paddington'
  | 'Park Royal'
  | 'Parsons Green'
  | 'Perivale'
  | 'Piccadilly Circus'
  | 'Pimlico'
  | 'Pinner'
  | 'Plaistow'
  | 'Poplar'
  | 'Preston Road'
  | 'Prince Regent'
  | 'Pudding Mill Lane'
  | 'Putney Bridge'
  | "Queen's Park"
  | 'Queensbury'
  | 'Queensway'
  | 'Ravenscourt Park'
  | 'Rayners Lane'
  | 'Redbridge'
  | "Regent's Park"
  | 'Richmond'
  | 'Rickmansworth'
  | 'Roding Valley'
  | 'Royal Albert'
  | 'Royal Oak'
  | 'Royal Victoria'
  | 'Ruislip'
  | 'Ruislip Gardens'
  | 'Ruislip Manor'
  | 'Russell Square'
  | 'Seven Sisters'
  | 'Shadwell'
  | "Shepherd's Bush"
  | "Shepherd's Bush Market"
  | 'Sloane Square'
  | 'Snaresbrook'
  | 'South Ealing'
  | 'South Harrow'
  | 'South Kensington'
  | 'South Kenton'
  | 'South Quay'
  | 'South Ruislip'
  | 'South Wimbledon'
  | 'South Woodford'
  | 'Southfields'
  | 'Southgate'
  | 'Southwark'
  | "St. James's Park"
  | "St. John's Wood"
  | "St. Paul's"
  | 'Stamford Brook'
  | 'Stanmore'
  | 'Stepney Green'
  | 'Stockwell'
  | 'Stonebridge Park'
  | 'Stratford'
  | 'Sudbury Hill'
  | 'Sudbury Town'
  | 'Surrey Docks'
  | 'Swiss Cottage'
  | 'Temple'
  | 'Theydon Bois'
  | 'Tooting Bec'
  | 'Tooting Broadway'
  | 'Tottenham Court Road'
  | 'Tottenham Hale'
  | 'Totteridge & Whetstone'
  | 'Tower Gateway'
  | 'Tower Hill'
  | 'Tufnell Park'
  | 'Turnham Green'
  | 'Turnpike Lane'
  | 'Upminster'
  | 'Upminster Bridge'
  | 'Upney'
  | 'Upton Park'
  | 'Uxbridge'
  | 'Vauxhall'
  | 'Victoria'
  | 'Walthamstow Central'
  | 'Wanstead'
  | 'Wapping'
  | 'Warren Street'
  | 'Warwick Avenue'
  | 'Waterloo'
  | 'Watford'
  | 'Wembley Central'
  | 'Wembley Park'
  | 'West Acton'
  | 'West Brompton'
  | 'West Finchley'
  | 'West Ham'
  | 'West Hampstead'
  | 'West Harrow'
  | 'West India Quay'
  | 'West Kensington'
  | 'West Ruislip'
  | 'West Silvertown'
  | 'Westbourne Park'
  | 'Westminster'
  | 'White City'
  | 'Whitechapel'
  | 'Willesden Green'
  | 'Willesden Junction'
  | 'Wimbledon'
  | 'Wimbledon Park'
  | 'Wood Green'
  | 'Woodford'
  | 'Woodside Park';

export default Station;
